// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: driver.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const available = `-- name: Available :execrows
UPDATE drivers 
SET 
is_available = TRUE,
updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) Available(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, available, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDriver = `-- name: CreateDriver :one
INSERT INTO drivers (
        id ,
    user_id 
)
VALUES(
    $1 ,
    $2
)
RETURNING id, user_id, is_online, is_available, current_latitude, current_longitude, rating, completed_rides, created_at, updated_at
`

type CreateDriverParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error) {
	row := q.db.QueryRow(ctx, createDriver, arg.ID, arg.UserID)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IsOnline,
		&i.IsAvailable,
		&i.CurrentLatitude,
		&i.CurrentLongitude,
		&i.Rating,
		&i.CompletedRides,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvailableDrivers = `-- name: GetAvailableDrivers :many
SELECT id, user_id, is_online, is_available, current_latitude, current_longitude, rating, completed_rides, created_at, updated_at 
FROM drivers 
WHERE is_available = TRUE
`

func (q *Queries) GetAvailableDrivers(ctx context.Context) ([]Driver, error) {
	rows, err := q.db.Query(ctx, getAvailableDrivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Driver{}
	for rows.Next() {
		var i Driver
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IsOnline,
			&i.IsAvailable,
			&i.CurrentLatitude,
			&i.CurrentLongitude,
			&i.Rating,
			&i.CompletedRides,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableDriversBYID = `-- name: GetAvailableDriversBYID :many
SELECT id
FROM drivers
WHERE id = ANY($1::uuid[])
AND is_available
AND is_online
`

func (q *Queries) GetAvailableDriversBYID(ctx context.Context, dollar_1 []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAvailableDriversBYID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDriverByUserId = `-- name: GetDriverByUserId :one
SELECT id, user_id, is_online, is_available, current_latitude, current_longitude, rating, completed_rides, created_at, updated_at FROM drivers WHERE user_id = $1
`

func (q *Queries) GetDriverByUserId(ctx context.Context, userID uuid.UUID) (Driver, error) {
	row := q.db.QueryRow(ctx, getDriverByUserId, userID)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IsOnline,
		&i.IsAvailable,
		&i.CurrentLatitude,
		&i.CurrentLongitude,
		&i.Rating,
		&i.CompletedRides,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const goOffline = `-- name: GoOffline :execrows
UPDATE drivers
SET
    is_online = FALSE,
    is_available = FALSE,
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) GoOffline(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, goOffline, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const goOnline = `-- name: GoOnline :execrows
UPDATE drivers
SET 
is_online = TRUE,
updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) GoOnline(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, goOnline, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unavailable = `-- name: Unavailable :execrows
UPDATE drivers 
SET 
is_available = FALSE,
updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) Unavailable(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, unavailable, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
