// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Driver struct {
	ID               uuid.UUID        `json:"id"`
	UserID           uuid.UUID        `json:"user_id"`
	IsOnline         bool             `json:"is_online"`
	IsAvailable      bool             `json:"is_available"`
	CurrentLatitude  pgtype.Numeric   `json:"current_latitude"`
	CurrentLongitude pgtype.Numeric   `json:"current_longitude"`
	Rating           pgtype.Numeric   `json:"rating"`
	CompletedRides   pgtype.Int4      `json:"completed_rides"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID        `json:"id"`
	FirstName    string           `json:"first_name"`
	LastName     string           `json:"last_name"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	Phone        string           `json:"phone"`
	Role         string           `json:"role"`
	ImageID      pgtype.UUID      `json:"image_id"`
	IsActive     bool             `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	LastLoginAt  pgtype.Timestamp `json:"last_login_at"`
}

type Vehicle struct {
	ID          uuid.UUID        `json:"id"`
	DriverID    uuid.UUID        `json:"driver_id"`
	Make        string           `json:"make"`
	Model       string           `json:"model"`
	Year        pgtype.Int4      `json:"year"`
	Color       pgtype.Text      `json:"color"`
	PlateNumber string           `json:"plate_number"`
	ImageFileID pgtype.UUID      `json:"image_file_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
