// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           pgtype.UUID      `json:"id"`
	FirstName    string           `json:"first_name"`
	LastName     string           `json:"last_name"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	Phone        string           `json:"phone"`
	Role         string           `json:"role"`
	ImageID      pgtype.UUID      `json:"image_id"`
	IsActive     bool             `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	LastLoginAt  pgtype.Timestamp `json:"last_login_at"`
}
