// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error
}

var _ Querier = (*Queries)(nil)
