// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error)
	GetDriverByUserId(ctx context.Context, userID uuid.UUID) (Driver, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GoOffline(ctx context.Context, userID uuid.UUID) error
	GoOnline(ctx context.Context, userID uuid.UUID) error
	UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
