// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rides_request.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRideReq = `-- name: CreateRideReq :one
INSERT INTO ride_requests (
        id,
    passenger_id,
    driver_id,

    pickup_latitude,
    pickup_longitude,

    destination_latitude,
    destination_longitude,

    pickup_address,
    destination_address,

    estimated_distance_km,
    estimated_duration_minutes,
    estimated_price,

    expires_at
)VALUES(
     $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id, passenger_id, driver_id, pickup_latitude, pickup_longitude, destination_latitude, destination_longitude, pickup_address, destination_address, estimated_distance_km, estimated_duration_minutes, estimated_price, status, expires_at, created_at, updated_at
`

type CreateRideReqParams struct {
	ID                       uuid.UUID        `json:"id"`
	PassengerID              uuid.UUID        `json:"passenger_id"`
	DriverID                 pgtype.UUID      `json:"driver_id"`
	PickupLatitude           pgtype.Numeric   `json:"pickup_latitude"`
	PickupLongitude          pgtype.Numeric   `json:"pickup_longitude"`
	DestinationLatitude      pgtype.Numeric   `json:"destination_latitude"`
	DestinationLongitude     pgtype.Numeric   `json:"destination_longitude"`
	PickupAddress            string           `json:"pickup_address"`
	DestinationAddress       string           `json:"destination_address"`
	EstimatedDistanceKm      pgtype.Numeric   `json:"estimated_distance_km"`
	EstimatedDurationMinutes int32            `json:"estimated_duration_minutes"`
	EstimatedPrice           pgtype.Numeric   `json:"estimated_price"`
	ExpiresAt                pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateRideReq(ctx context.Context, arg CreateRideReqParams) (RideRequest, error) {
	row := q.db.QueryRow(ctx, createRideReq,
		arg.ID,
		arg.PassengerID,
		arg.DriverID,
		arg.PickupLatitude,
		arg.PickupLongitude,
		arg.DestinationLatitude,
		arg.DestinationLongitude,
		arg.PickupAddress,
		arg.DestinationAddress,
		arg.EstimatedDistanceKm,
		arg.EstimatedDurationMinutes,
		arg.EstimatedPrice,
		arg.ExpiresAt,
	)
	var i RideRequest
	err := row.Scan(
		&i.ID,
		&i.PassengerID,
		&i.DriverID,
		&i.PickupLatitude,
		&i.PickupLongitude,
		&i.DestinationLatitude,
		&i.DestinationLongitude,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.EstimatedDistanceKm,
		&i.EstimatedDurationMinutes,
		&i.EstimatedPrice,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
