// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicle.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVehicle = `-- name: CreateVehicle :one

INSERT INTO vehicles (
    id,
    driver_id,
    make,
    model,
    year,
    color,
    plate_number,
    image_file_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, driver_id, make, model, year, color, plate_number, image_file_id, created_at, updated_at
`

type CreateVehicleParams struct {
	ID          uuid.UUID   `json:"id"`
	DriverID    uuid.UUID   `json:"driver_id"`
	Make        string      `json:"make"`
	Model       string      `json:"model"`
	Year        pgtype.Int4 `json:"year"`
	Color       pgtype.Text `json:"color"`
	PlateNumber string      `json:"plate_number"`
	ImageFileID pgtype.UUID `json:"image_file_id"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.ID,
		arg.DriverID,
		arg.Make,
		arg.Model,
		arg.Year,
		arg.Color,
		arg.PlateNumber,
		arg.ImageFileID,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Color,
		&i.PlateNumber,
		&i.ImageFileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
